environments:
  local:
    base_raw: "${LAKE_ROOT}/raw/demodados/camara"
    base_bronze: "${LAKE_ROOT}/bronze/demodados/camara"
    base_error: "${LAKE_ROOT}/raw/demodados/camara/error"
    base_parameters: "${LAKE_ROOT}/raw/demodados/camara/parameters"
  airflow:
    base_raw: "/usr/local/airflow/mylake/raw/demodados/camara"
    base_bronze: "/usr/local/airflow/mylake/bronze/demodados/camara"
    base_error: "/usr/local/airflow/mylake/raw/demodados/camara/error"
    base_parameters: "/usr/local/airflow/mylake/raw/demodados/camara/parameters"

sources:
  legislatura:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/deputados/"
    subpath: "legislatura"
    bronze_file: "legislaturas_deputados.csv"
    db_table: "raw_camara_legislaturas"

  deputados:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/deputados/"
    subpath: "deputados"
    bronze_file: "parlamento_deputados.csv"
    db_table: "raw_camara_deputados"
    parameter_file: "id_deputados.csv"

  votacoes:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/votacoes"
    subpath: "votacoes"
    bronze_file: "camara_votacoes.csv"
    db_table: "raw_camara_votacoes"
    output_param_file: 
      id_votacoes.csv: "id"
      id_proposicao.csv: "id_proposicao"

  votos_deputados:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/votacoes/"
    subpath: "votos_deputados"
    bronze_file: "camara_votos_deputados.csv"
    db_table: "raw_camara_votos_deputados"
    parameter_file: "id_votacoes.csv"

  votos_orientacao:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/votacoes/"
    subpath: "votos_orientacao"
    bronze_file: "camara_votos_orientacao.csv"
    db_table: "raw_camara_votos_orientacao"
    parameter_file: "id_votacoes.csv"

  proposicao_tema:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/proposicoes/"
    subpath: "proposicao_tema"
    bronze_file: "camara_proposicao_tema.csv"
    db_table: "raw_camara_proposicao_tema"
    parameter_file: "id_proposicao.csv"

  proposicao:
    base_url: "https://dadosabertos.camara.leg.br/api/v2/proposicoes/"
    subpath: "proposicao"
    bronze_file: "camara_proposicao.csv"
    db_table: "raw_camara_proposicao"
    parameter_file: "id_proposicao.csv"